// Copyright (c) Edgeless Systems GmbH.
// Licensed under the MIT License.

#include <openenclave/ert_args.h>
#include <openenclave/host.h>
#include <cpuid.h>
#include <limits.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Generated by oeedger8r from emain.edl.
#include "emain_u.h"

#include "libsgxstep/apic.h"
#include "libsgxstep/cache.h"
#include "libsgxstep/config.h"
#include "libsgxstep/debug.h"
#include "libsgxstep/enclave.h"
#include "libsgxstep/idt.h"
#include "libsgxstep/pt.h"
#include "libsgxstep/sched.h"

oe_enclave_t *enclave = NULL;
int irq_cnt = 0, do_irq = 1;
int timer_interval = SGX_STEP_TIMER_INTERVAL;
int max_irq = 100000;
uint64_t *pmd_encl = NULL;
int info_registered = 0;

/* ================== EDGELESS RT HOST OCALLS ================= */
/* erthost's args/cpuid ocalls, required by an ertdeventry (EGo) enclave. */

extern char **environ;
static ert_args_t _args;

static void init_args(int argc, char **argv, char **envp) {
    _args.argc = argc;
    _args.argv = argv;
    _args.envp = envp;
    while (envp[_args.envc]) ++_args.envc;
    _args.auxv = (const long *)(_args.envp + _args.envc + 1);
    while (_args.auxv[2 * _args.auxc] || _args.auxv[2 * _args.auxc + 1])
        ++_args.auxc;
    char cwd[PATH_MAX];
    if (getcwd(cwd, sizeof(cwd)))
        setenv("EDG_CWD", cwd, 0);
    _args.envp = environ;
    ++_args.envc;
}

ert_args_t ert_get_args_ocall(void) { return _args; }

void ert_cpuid_ocall(unsigned int leaf, unsigned int subleaf, unsigned int *eax,
                     unsigned int *ebx, unsigned int *ecx, unsigned int *edx) {
    __cpuid_count(leaf, subleaf, *eax, *ebx, *ecx, *edx);
}

/* ================== APIC RESTORE ON ANY EXIT ================= */

/*
 * step_close() restores the victim core's APIC tick; without it, enclave teardown
 * hangs in synchronize_srcu (issue #90). The destructor covers a normal return,
 * these handlers an abort/crash/^C.
 */
static void restore_and_die(int sig) {
    step_close();
    signal(sig, SIG_DFL);
    raise(sig);
}

static void install_apic_restore_guards(void) {
    atexit(step_close);
    int sigs[] = {SIGINT, SIGTERM, SIGABRT, SIGSEGV, SIGBUS, SIGILL, SIGFPE};
    for (unsigned i = 0; i < sizeof(sigs) / sizeof(sigs[0]); i++)
        signal(sigs[i], restore_and_die);
}

/* Called before resuming the enclave after an Asynchronous Enclave eXit. */
void aep_cb_func(void) {
    /* single-stepping stopped; ignore the free-run AEXs */
    if (!do_irq)
        return;
    /*
     * emain runs the whole Go program in one ECALL, so there is no dry run to arm
     * single-stepping first; register the enclave info on the first AEX instead.
     */
    if (!info_registered) {
        register_enclave_info();
        print_enclave_info();
        ASSERT(pmd_encl = remap_page_table_level(get_enclave_base(), PMD));
        info_registered = 1;
    }

    uint64_t erip = edbgrd_erip() - (uint64_t)get_enclave_base();
    info("^^ enclave RIP=%#09llx", erip);
    irq_cnt++;

    if (do_irq && irq_cnt > max_irq) {
        info("interrupt budget exhausted; restoring APIC and letting the enclave "
             "run to completion");
        do_irq = 0;
        /* restore the tick before free-run so a kill can't wedge the machine (#90) */
        step_close();
    }

    /*
     * Scanning the whole Go enclave's exec range for accessed bits is too slow, so
     * we skip zero-step filtering and only widen the landing window via the PMD.
     */
    if (do_irq) {
        *pmd_encl = MARK_NOT_ACCESSED(*pmd_encl);
        flush(pmd_encl);
        apic_timer_irq(timer_interval);
    }
}

int main(int argc, char **argv, char **envp) {
    idt_t idt = {0};
    init_args(argc, argv, envp);

    int opt;
    while ((opt = getopt(argc, argv, "t:m:")) != -1) {
        switch (opt) {
        case 't': timer_interval = atoi(optarg); break;
        case 'm': max_irq        = atoi(optarg); break;
        }
    }
    if (optind >= argc) {
        fprintf(stderr, "Usage: %s [-t timer_interval] [-m max_irq] enclave\n",
                argv[0]);
        return 1;
    }
    const char *encl_path = argv[optind];

    const char *sim = getenv("OE_SIMULATION");
    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG |
                     ((sim && *sim == '1') ? OE_ENCLAVE_FLAG_SIMULATE : 0);

    info_event("Creating EGo/Edgeless RT enclave...");
    if (oe_create_emain_enclave(encl_path, OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0,
                                &enclave) != OE_OK ||
        !enclave) {
        fprintf(stderr, "oe_create_emain_enclave failed\n");
        return 1;
    }

    /* 1. Setup attack execution environment. */
    ASSERT(!claim_cpu(VICTIM_CPU));
    ASSERT(!prepare_system_for_benchmark(PSTATE_PCT));
    print_system_settings();
    register_aep_cb(aep_cb_func);

    info_event("Establishing user-space APIC/IDT mappings");
    map_idt(&idt);
    install_kernel_irq_handler(&idt, __ss_irq_handler, IRQ_VECTOR);
    install_apic_restore_guards();
    apic_timer_oneshot(IRQ_VECTOR);

    __ss_irq_fired = 0;
    apic_timer_irq(timer_interval);
    while (!__ss_irq_fired);
    info("APIC timer IRQ handler seems to be working");

    /*
     * 2. Single-step. The Go start-up is long, so the first IRQ armed here lands
     * in the enclave, and aep_cb_func re-arms the timer after each step.
     */
    info_event("entering enclave: timer=%d", timer_interval);
    __ss_irq_fired = 0;
    apic_timer_irq(timer_interval);

    int ret = 1;
    if (emain(enclave, &ret) != OE_OK)
        fprintf(stderr, "emain ecall failed\n");

    do_irq = 0;
    step_close(); /* restore the APIC tick immediately, not via the destructor */
    info_event("all done; counted %d/%d IRQs (AEP/IDT)", irq_cnt,
               __ss_irq_count);

    /* No oe_terminate_enclave: step_close() restored the tick, and destroying with
     * the APIC still hijacked would hang (issue #90). */
    return 0;
}
